quarkus.banner.enabled=false
quarkus.log.category."io.quarkus".level=WARN
quarkus.log.category."org.apache.http".level=ERROR
quarkus.log.category."dev.streamx".level=ERROR
%debug.quarkus.log.category."dev.streamx".level=DEBUG