name: 'CI: Deploy SNAPSHOT Maven'

on:
  push:
    branches:
#      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_STREAMX_RELEASES_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_STREAMX_RELEASES_SNAPSHOT_DEPLOY_SA }}
          token_format: access_token

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to GAR
#        uses: docker/login-action@v2
#        with:
#          registry: ${{ vars.GAR_DOCKER_REGISTRY }}
#          username: oauth2accesstoken
#          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build and deploy artifacts
        run: ./mvnw clean deploy