name: StreamX Scoop Installation Check

on:
  workflow_dispatch:

jobs:
  check-scoop-installation:

    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Scoop
        uses: MinoruSekine/setup-scoop@v4

      - name: Install StreamX via Scoop and validate installation 
        run: |
          scoop bucket add streamx-dev https://github.com/streamx-dev/scoop-streamx-dev.git
          scoop install streamx

          $output = (streamx --version --accept-license) | Out-String
          $expected_fragment = "streamx-cli version:"
          if (-not $output.Contains($expected_fragment)) {
            Write-Output "Error: Expected output to contain '$expected_fragment', but got: $output"
            exit 1
          } else {
            Write-Output "Output: '$output' contains '$expected_fragment'."
          }
